apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: abdelhamid-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ahmed1399/backend-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          # value: "mongodb://mongo-0.mongo-service:27017/counterdb?directConnection=true"
          value: "mongodb://mongo-0.mongo-service.abdelhamid-ns.svc.cluster.local:27017/counterdb?directConnection=true"
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: abdelhamid-ns
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
